- hosts: localhost
  vars:
    - ansible_python_interpreter: "/usr/bin/python3"
  vars_files:
    - /home/ubuntu/ansible-working/vault/testing.yml

  tasks:
    - name: Create a GitHub Repo
      github_repo:
        github_auth_key:  "{{ token }}" 
        username: "c-poteat"
        name: "Hello-World"
        description: "First repo created with custom Ansible module"
        private: yes
        has_issues: no
        has_wiki: no
        has_downloads: no
        state: present
      register: result
      tags: 
       - add
    
    - name: Delete GitHub Repo
      github_repo:
        github_auth_key:  "{{ token }}" 
        username: "c-poteat"
        name: "Hello-World"
        state: absent
      tags:
        - delete
